/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
 
/* deno-fmt-ignore-file */

declare module 'sst' {
  export interface Resource {
    frontend: {
      type: 'sst.aws.Nextjs';
    };
  }
}
/// <reference path="sst-env.d.ts" />

import 'sst';
export {};
